name: Push Notify
# This workflow is triggered on pushes to the repository.
on: [push]
jobs:
  notify:
    name: Notify
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: 'Sending SMS Notification'
        uses: twilio-labs/actions-sms@v1
        with:
          fromPhoneNumber: '+1(516)271-3927'
          toPhoneNumber: '+1(415)2907984'
          message: 'D00D!! maze-maze repo updated at GitHub, please update S3 bucket!'
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
          TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}
